pull_request_rules:
  - name: automatic merge on CI success and review
      conditions:
        - "status-success=ci/circleci: validate"
        - "#approved-reviews-by>=1"
      actions:
        merge:
          method: merge